import streamlit as st
from model import predict
st.set_page_config(page_title="AI Text Detector", layout="centered")
st.title("AI vs Human Text Detection System")
st.write("Enter text to classify whether it is AI-generated or Human-written.")
#input
user_text = st.text_area("Enter your text here:")
#model selection
model_choice = st.selectbox("Select Model",["Logistic Regression", "Random Forest", "Gradient Boosting", "XGBoost"])
# threshold 
threshold = st.slider("Confidence Threshold", 0.0, 1.0, 0.6)
# Button
if st.button("Analyze Text"):
    if user_text.strip() == "":
        st.warning("Please enter some text!")
    else:
        label, confidence, decision = predict(user_text, model_choice, threshold)
        st.subheader("Result")
        if label == "AI":
            st.error("Text generated by AI")
        else:
            st.success("Text generated by Human")
        st.write(f"**Prediction:** {label}")
        st.write(f"**Confidence:** {confidence:.4f}")
        st.write(f"**Decision:** {decision}")
st.info("Tip: Try different models and thresholds to compare results!")